# Generated by Django 5.2.4 on 2025-08-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0006_alter_pantryitem_pantry'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourited_products',
            field=models.ManyToManyField(related_name='favourited_by', to='pantry.product'),
        ),
    ]
