# Generated by Django 5.2.4 on 2025-09-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='country',
            new_name='language_preference',
        ),
    ]
