# Generated by Django 5.2.4 on 2025-10-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_get_only_localised_results_usersettings_prioritise_local_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language_preference',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
