# Generated by Django 5.2.4 on 2025-10-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersettings_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='scan_to_add',
            field=models.BooleanField(default=False),
        ),
    ]
