# Generated by Django 5.2.4 on 2025-09-08 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pantry', '0002_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedrecipeingredient',
            name='pantry_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.product'),
        ),
        migrations.AddField(
            model_name='savedrecipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.savedrecipe'),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='used_in_recipes', through='recipes.SavedRecipeIngredient', to='pantry.product'),
        ),
        migrations.AddField(
            model_name='suggestedrecipe',
            name='used_ingredients',
            field=models.ManyToManyField(related_name='suggested_recipes_used_in', to='pantry.product'),
        ),
        migrations.AddField(
            model_name='suggestedrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedrecipeingredient',
            unique_together={('recipe', 'pantry_item')},
        ),
    ]
