# Generated by Django 5.2.4 on 2025-08-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_delete_newmodel_remove_pantryitem_newfield'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedrecipe',
            name='recipe_text',
        ),
        migrations.AddField(
            model_name='suggestedrecipe',
            name='recipe_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='suggestedrecipe',
            name='used_ingredients',
            field=models.ManyToManyField(related_name='suggested_recipes_used_in', to='pantry.pantryitem'),
        ),
    ]
