# Generated by Django 5.2.4 on 2025-09-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_initial'),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedrecipeingredient',
            old_name='pantry_item',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='savedrecipeingredient',
            unique_together={('recipe', 'product')},
        ),
    ]
