# Generated by Django 5.2.4 on 2025-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_suggestedrecipe_recipe_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedrecipe',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('recent', 'Recent'), ('seen', 'Seen'), ('saved', 'Saved'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='new', max_length=10),
        ),
    ]
