# Generated by Django 5.2.4 on 2025-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_suggestedrecipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(),
        ),
    ]
