# Generated by Django 5.2.4 on 2025-08-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedrecipe',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suggestedrecipe',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('recent', 'Recent'), ('saved', 'Saved'), ('deleted', 'Deleted')], default='new', max_length=10),
        ),
    ]
