# Generated by Django 5.2.4 on 2025-07-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('brands', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('serving_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('serving_per_container', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_quantity_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('product_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('allergens', models.TextField(blank=True, null=True)),
                ('energy_kj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saturated_fat_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrates_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugars_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saturated_fat_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrates_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugars_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nutrition_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nutrition_grade', models.CharField(blank=True, max_length=1, null=True)),
                ('nova_group', models.CharField(blank=True, max_length=50, null=True)),
                ('ecoscore_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ecoscore_grade', models.CharField(blank=True, max_length=1, null=True)),
                ('manufacturing_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
