# Generated by Django 5.2.4 on 2025-07-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantryitem',
            name='unit',
        ),
    ]
