# Generated by Django 5.2.4 on 2025-09-08 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pantry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='pantry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='pantry.pantry'),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_entries', to='pantry.product'),
        ),
        migrations.AddField(
            model_name='pantry',
            name='products',
            field=models.ManyToManyField(related_name='contained_in_pantries', through='pantry.PantryItem', to='pantry.product'),
        ),
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together={('pantry', 'product')},
        ),
    ]
