# Generated by Django 5.2.4 on 2025-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_remove_pantryitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newfield', models.CharField(max_length=255)),
            ],
        ),
    ]
