# Generated by Django 5.2.4 on 2025-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
