# Generated by Django 5.2.4 on 2025-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_product_labels_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
