# Generated by Django 5.2.4 on 2025-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_newmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='newfield',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
