# Generated by Django 5.2.4 on 2025-07-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_pantryitem_newfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
        migrations.RemoveField(
            model_name='pantryitem',
            name='newfield',
        ),
    ]
