# Generated by Django 5.2.4 on 2025-08-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_delete_newmodel_remove_pantryitem_newfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='pantry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='pantry.pantry'),
        ),
    ]
